const Languages = [{
  "Afrikaans": "af-ZA",
  "Albanian": "sq-AL",
  "Amharic": "am-ET",
  "Arabic": "ar-SA",
  "Armenian": "hy-AM",
  "Azerbaijani": "az-AZ",
  "Bengali": "bn-BD",
  "Bosnian": "bs-BA",
  "Bulgarian": "bg-BG",
  "Catalan": "ca-ES",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Traditional)": "zh-TW",
  "Croatian": "hr-HR",
  "Czech": "cs-CZ",
  "Danish": "da-DK",
  "Dari": "fa-AF",
  "Dutch": "nl-NL",
  "English": "en-US",
  "Estonian": "et-EE",
  "Farsi (Persian)": "fa-IR",
  "Filipino, Tagalog": "tl-PH",
  "Finnish": "fi-FI",
  "French": "fr-FR",
  "French (Canada)": "fr-CA",
  "Georgian": "ka-GE",
  "German": "de-DE",
  "Greek": "el-GR",
  "Gujarati": "gu-IN",
  "Haitian Creole": "ht-HT",
  "Hausa": "ha-NG",
  "Hebrew": "he-IL",
  "Hindi": "hi-IN",
  "Hungarian": "hu-HU",
  "Icelandic": "is-IS",
  "Indonesian": "id-ID",
  "Irish": "ga-IE",
  "Italian": "it-IT",
  "Japanese": "ja-JP",
  "Kannada": "kn-IN",
  "Kazakh": "kk-KZ",
  "Korean": "ko-KR",
  "Latvian": "lv-LV",
  "Lithuanian": "lt-LT",
  "Macedonian": "mk-MK",
  "Malay": "ms-MY",
  "Malayalam": "ml-IN",
  "Maltese": "mt-MT",
  "Marathi": "mr-IN",
  "Mongolian": "mn-MN",
  "Norwegian (Bokmål)": "no-NO",
  "Pashto": "ps-AF",
  "Polish": "pl-PL",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  "Punjabi": "pa-IN",
  "Romanian": "ro-RO",
  "Russian": "ru-RU",
  "Serbian": "sr-RS",
  "Sinhala": "si-LK",
  "Slovak": "sk-SK",
  "Slovenian": "sl-SI",
  "Somali": "so-SO",
  "Spanish": "es-ES",
  "Spanish (Mexico)": "es-MX",
  "Swahili": "sw-KE",
  "Swedish": "sv-SE",
  "Tamil": "ta-IN",
  "Telugu": "te-IN",
  "Thai": "th-TH",
  "Turkish": "tr-TR",
  "Ukrainian": "uk-UA",
  "Urdu": "ur-PK",
  "Uzbek": "uz-UZ",
  "Vietnamese": "vi-VN",
  "Welsh": "cy-GB"
}];

export default Languages;
